version: '3'

services:
  postgresql:
    image: postgres
    container_name: barbershop
    ports:
      - '5433:5432'  # Змінив порт на 5433
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=barbershop
      - POSTGRES_PASSWORD=barbershop
      - POSTGRES_DATABASE=barbershop
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-barbershop
    ports:
      - '6379:6379'  # Змінив порт на 6379